# Generated by Django 4.2 on 2024-12-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Newapp', '0002_imagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='message',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='name',
            field=models.CharField(max_length=400),
        ),
    ]
